### PR TITLE
Use MAILER_URL for mailer url in dev

### LINKED ISSUE #29: Local development confirmation email uses localhost:3000
The email uses `localhost:3000` as the hostname for the confirmation link.

### PR DESCRIPTION
**Pull request by kmiyashiro**
fixes https://github.com/DevProgress/HillaryBNB/issues/29

### CODE REVIEW

**Comment by dsjoerg** [comment]
Does this work in your dev env?  Without the port, I would expect that it wouldn't work in the dev env.

**Comment by kmiyashiro** [comment]
You can set the port in the URL itself, similar to the example in the test env: https://github.com/DevProgress/HillaryBNB/blob/master/config/environments/test.rb#L42

**Comment by dsjoerg** [comment]
Got it.  So people are going to set MAILER_URL to something like `"localhost:3000"` or `hbnb.com:3000` in their application.yml, I take it?

**Comment by kmiyashiro** [comment]
Actually, I just tried this and the tests are wrong. Mailgun will reject a request with a port in the host. I'll update with fix, but may be some breaking changes since the variable name doesn't make sense anymore.

**Comment by kmiyashiro** [comment]
Disregard my last comment, the issue is unrelated. Mailgun just seems to be returning 400 for all my requests.

```
Mailgun::CommunicationError (400 Bad Request):
  app/mailers/user_mailer.rb:60:in `deliver_message'
  app/mailers/user_mailer.rb:8:in `registration_confirmation'
  app/controllers/users_controller.rb:19:in `update'
```

**Comment by kmiyashiro** [comment]
Ugh, very non-description error. Turns out I was testing an email that wasn't in my authorized recipients for my sandbox mailgun account. Yes, confirmed that adding the port to `MAILER_URL` works as expected.

**Comment by mt0321** [comment]
Is there any reason why config/environments/test.rb should not be set up the same way? That still has localhost:3000 hard-coded there. Is it because the tests rely on that?

**Comment by kmiyashiro** [comment]
I think it's fine for the test env to be hardcoded. Side note: when I tried
running the tests, 30 of them failed. It seems that it's making real
requests and not stubbed ones.

**Comment by dsjoerg** [comment]
When I run the tests they all pass.  @kmiyashiro i have encountered the problem you mentioned in testing, where it's attempting to make real requests.  the README's suggested test command `RAILS_ENV=test docker-compose run shell bash -c 'bin/rake db:migrate && bin/rake'` sets the RAILS_ENV to test, and then in application.yml I have it set up so that MAILGUN_\* is only configured for development and production.  similar to how application.yml.example only defines MAILGUN_\* for development.

**Comment by kmiyashiro** [comment]
Yup, just tried it again after adding a `development` section to the yml for `MAILGUN_*`, not sure why it wasn't separated to begin with. This command and others should probably be made into scripts for convenience.

**Pull request merged**
